-- Seed data for ClearNest.
--
-- NOTE: We intentionally DO NOT seed fake testimonials. ClearNest is a new
-- business — showing fabricated reviews is false advertising and erodes trust.
-- Real reviews are added by the owner via /admin/reviews once collected.
--
-- The public site automatically shows a "founding customer" trust section
-- whenever the reviews table is empty, and switches to real reviews as soon
-- as you add them.

-- (No inserts. Add real reviews through the admin panel.)
